In [2]:
import pandas as pd
import numpy as np

# Load the ratings by user information that you collected into a pandas dataframe.

In [3]:
originalData = pd.read_csv('Week 7 - Aggregating Data.csv')
data = originalData.copy()
data

,Timestamp,Total score,Name,Name [Score],Name [Feedback],Movies [Jojo Rabbit],Movies [Jojo Rabbit] [Score],Movies [Frozen 2],Movies [Frozen 2] [Score],Movies [Star Wars: Rise of Skywalker],Movies [Star Wars: Rise of Skywalker] [Score],Movies [Joker],Movies [Joker] [Score],Movies [Parasite],Movies [Parasite] [Score],Movies [Killer Klowns from Outer Space],Movies [Killer Klowns from Outer Space] [Score]
0,2020/03/12 12:45:29 PM AST,0.00 / 0,Tiffany Williams,-- / 0,NaN,Haven't Watched,-- / 0,2,-- / 0,Haven't Watched,-- / 0,1,-- / 0,4,-- / 0,5,-- / 0
1,2020/03/12 12:50:31 PM AST,0.00 / 0,Patrick,-- / 0,NaN,4,-- / 0,4,-- / 0,4,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,3,-- / 0
2,2020/03/12 12:53:08 PM AST,0.00 / 0,Andrew stern,-- / 0,NaN,3,-- / 0,1,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,2,-- / 0
3,2020/03/12 1:03:34 PM AST,0.00 / 0,Michelle,-- / 0,NaN,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0
4,2020/03/12 2:10:11 PM AST,0.00 / 0,Pam Kubisiak,-- / 0,NaN,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0
5,2020/03/12 2:27:20 PM AST,0.00 / 0,Dunn,-- / 0,NaN,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,1,-- / 0
6,2020/03/12 2:54:11 PM AST,0.00 / 0,Liz,-- / 0,NaN,1,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,3,-- / 0
7,2020/03/12 5:10:26 PM AST,0.00 / 0,patrick daley,-- / 0,NaN,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0
8,2020/03/12 8:46:17 PM AST,0.00 / 0,Me!,-- / 0,NaN,4,-- / 0,3,-- / 0,3,-- / 0,3,-- / 0,3,-- / 0,1,-- / 0
9,2020/03/12 9:31:37 PM AST,0.00 / 0,Phyllis,-- / 0,NaN,2,-- / 0,Haven't Watched,-- / 0,5,-- / 0,3,-- / 0,1,-- / 0,4,-- / 0
10,2020/03/12 10:36:40 PM AST,0.00 / 0,Mary,-- / 0,NaN,Haven't Watched,-- / 0,3,-- / 0,5,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0
11,2020/03/13 8:33:23 AM AST,0.00 / 0,Paul,-- / 0,NaN,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0

NaN values changed to 0 for readability.

In [4]:
data.set_index('Name', inplace = True)
data.fillna('0')

,Timestamp,Total score,Name [Score],Name [Feedback],Movies [Jojo Rabbit],Movies [Jojo Rabbit] [Score],Movies [Frozen 2],Movies [Frozen 2] [Score],Movies [Star Wars: Rise of Skywalker],Movies [Star Wars: Rise of Skywalker] [Score],Movies [Joker],Movies [Joker] [Score],Movies [Parasite],Movies [Parasite] [Score],Movies [Killer Klowns from Outer Space],Movies [Killer Klowns from Outer Space] [Score]
Name,,,,,,,,,,,,,,,,
Tiffany Williams,2020/03/12 12:45:29 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,2,-- / 0,Haven't Watched,-- / 0,1,-- / 0,4,-- / 0,5,-- / 0
Patrick,2020/03/12 12:50:31 PM AST,0.00 / 0,-- / 0,0,4,-- / 0,4,-- / 0,4,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,3,-- / 0
Andrew stern,2020/03/12 12:53:08 PM AST,0.00 / 0,-- / 0,0,3,-- / 0,1,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,2,-- / 0
Michelle,2020/03/12 1:03:34 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0
Pam Kubisiak,2020/03/12 2:10:11 PM AST,0.00 / 0,-- / 0,0,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0
Dunn,2020/03/12 2:27:20 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,1,-- / 0
Liz,2020/03/12 2:54:11 PM AST,0.00 / 0,-- / 0,0,1,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,3,-- / 0
patrick daley,2020/03/12 5:10:26 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0
Me!,2020/03/12 8:46:17 PM AST,0.00 / 0,-- / 0,0,4,-- / 0,3,-- / 0,3,-- / 0,3,-- / 0,3,-- / 0,1,-- / 0
Phyllis,2020/03/12 9:31:37 PM AST,0.00 / 0,-- / 0,0,2,-- / 0,Haven't Watched,-- / 0,5,-- / 0,3,-- / 0,1,-- / 0,4,-- / 0
Mary,2020/03/12 10:36:40 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,3,-- / 0,5,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0
Paul,2020/03/13 8:33:23 AM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0

# Show the average ratings for each user and each movie.

In [5]:
usermean = data.mean(axis=1, skipna=True, numeric_only=True)
data['User Mean Ratings'] = usermean
moviemean = data.mean(axis=0, skipna=True, numeric_only=True)
data.loc['Mean Movie Rating'] = moviemean
movieOut = data.loc[['Mean Movie Rating']]
movieOut.drop('User Mean Ratings', inplace=True, axis=1)
data.fillna('0')

,Timestamp,Total score,Name [Score],Name [Feedback],Movies [Jojo Rabbit],Movies [Jojo Rabbit] [Score],Movies [Frozen 2],Movies [Frozen 2] [Score],Movies [Star Wars: Rise of Skywalker],Movies [Star Wars: Rise of Skywalker] [Score],Movies [Joker],Movies [Joker] [Score],Movies [Parasite],Movies [Parasite] [Score],Movies [Killer Klowns from Outer Space],Movies [Killer Klowns from Outer Space] [Score],User Mean Ratings
Name,,,,,,,,,,,,,,,,,
Tiffany Williams,2020/03/12 12:45:29 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,2,-- / 0,Haven't Watched,-- / 0,1,-- / 0,4,-- / 0,5,-- / 0,0
Patrick,2020/03/12 12:50:31 PM AST,0.00 / 0,-- / 0,0,4,-- / 0,4,-- / 0,4,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,3,-- / 0,0
Andrew stern,2020/03/12 12:53:08 PM AST,0.00 / 0,-- / 0,0,3,-- / 0,1,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,2,-- / 0,0
Michelle,2020/03/12 1:03:34 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,0
Pam Kubisiak,2020/03/12 2:10:11 PM AST,0.00 / 0,-- / 0,0,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0,1,-- / 0,0
Dunn,2020/03/12 2:27:20 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,1,-- / 0,0
Liz,2020/03/12 2:54:11 PM AST,0.00 / 0,-- / 0,0,1,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,3,-- / 0,0
patrick daley,2020/03/12 5:10:26 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,0
Me!,2020/03/12 8:46:17 PM AST,0.00 / 0,-- / 0,0,4,-- / 0,3,-- / 0,3,-- / 0,3,-- / 0,3,-- / 0,1,-- / 0,0
Phyllis,2020/03/12 9:31:37 PM AST,0.00 / 0,-- / 0,0,2,-- / 0,Haven't Watched,-- / 0,5,-- / 0,3,-- / 0,1,-- / 0,4,-- / 0,0
Mary,2020/03/12 10:36:40 PM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,3,-- / 0,5,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,0
Paul,2020/03/13 8:33:23 AM AST,0.00 / 0,-- / 0,0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,Haven't Watched,-- / 0,0
Mean Movie Rating,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

# Create a new pandas dataframe, with normalized ratings for each user. Again, show the average ratings for each user and each movie.

In [126]:
normalData = (data - data.min()) / (data.max() - data.min())
normalData.fillna('0')

,Jojo Rabbit,Frozen 2,Star Wars: Rise of Skywalker,Joker,Parasite,Killer Klowns from Outer Space,User Mean Ratings
Name,,,,,,,
Tiffany Williams,0,0.333333,0,0,1,1,0.666667
Patrick,1,1,0.75,0,0,0.5,0.916667
Andrew stern,0.666667,0,0,0,0,0.25,0.333333
Michelle,0,0,0,0,0,0,0
Pam Kubisiak,0,0,0,0,0,0,0
Dunn,0,0,0,0,0,0,0
Liz,0,0,0,0,0,0.5,0.333333
patrick daley,0,0,0,0,0,0,0
Amanda,1,0.666667,0.5,1,0.666667,0,0.611111
Phyllis,0,0,0.75,0.5,0,0.75,0.466667
Mary,0,0.666667,1,0,0,0,1
Paul,0,0,0,0,0,0,0
Eric,0,0,0,0,0,0.5,0.333333
Mean Movie Rating,0.444444,0.444444,0.6,0.3,0.416667,0.388889,0.466467

# Provide a text-based conclusion: explain what might be advantages and disadvantages of using normalized ratings instead of the actual ratings.

Normalizing the data will remove any outliers and put the data on a common scale.  By putting the data on a common sclae the original values are changed.

With my data 1 being the highest rating and 5 being the lowest, normalizing the data only confuses the viewer.

# [Extra credit] Create another new pandas dataframe, with standardized ratings for each user. Once again, show the average ratings for each user and each movie.

In [137]:
standardData = ((data - data.mean()) / data.std())
standardData.fillna('0')

,Jojo Rabbit,Frozen 2,Star Wars: Rise of Skywalker,Joker,Parasite,Killer Klowns from Outer Space
Name,,,,,,
Tiffany Williams,0,-0.275241,0,-0.67082,1.16667,1.7166
Patrick,1.10702,1.3762,0.395628,0,0,0.31211
Andrew stern,0.442807,-1.10096,0,0,0,-0.390137
Michelle,0,0,0,0,0,0
Pam Kubisiak,-0.885615,-1.10096,-1.58251,-0.67082,-0.833333,-1.09238
Dunn,0,0,0,0,0,-1.09238
Liz,-0.885615,0,0,0,0,0.31211
patrick daley,0,0,0,0,0,0
Amanda,1.10702,0.550482,-0.263752,1.56525,0.5,-1.09238
Phyllis,-0.885615,0,0.395628,0.447214,-0.833333,1.01436
Mary,0,0.550482,1.05501,0,0,0
Paul,0,0,0,0,0,0
Eric,0,0,0,-0.67082,0,0.31211